In [11]:
#empty and full array ones array
import numpy as np
arr1 = np.empty([3,3])
print(arr1,"\n")
arr2 = np.full((3,4),33)
print(arr2)
arr3 = np.ones((2,3))
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[33 33 33 33]
 [33 33 33 33]
 [33 33 33 33]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
#checking rows in an array
arr = np.arange(1,21).reshape(4,5)
print(arr)
print("\n List of Array elements :",arr.tolist())  #tolist converts the array into a list of each elemnts as rows
print("\n[1,2,3,4,5] in array :",[1,2,3,4,5] in arr.tolist())
print("\n[6,7,8,9,10] in array :",[6,7,8,9,10] in arr.tolist())
print("\n[21,22,34,35] in array :",[21,22,34,35] in arr.tolist())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

 List of Array elements : [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]

[1,2,3,4,5] in array : True

[6,7,8,9,10] in array : True

[21,22,34,35] in array : False


In [107]:
#removing rows containing nan values 
arr = np.array([[1,2,3],[4,5,6],[7,np.nan,np.nan]])
print(arr)
print(arr[~np.isnan(arr).any(axis=1)])

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7. nan nan]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [42]:
#remove single dimenssion from an array
arr = np.arange(9).reshape(1,3,3)
print(arr)
print("arrar shape : ",arr.shape)
arr = np.squeeze(arr) #if there is single dimenssion in an multidimenssional array it squeezes out it to shorten dimession
print("\n",arr)
print("\nShape of array now",arr.shape)

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]
arrar shape :  (1, 3, 3)

 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Shape of array now (3, 3)


In [50]:
arr = np.array([[2,8,9,4], 
                   [9,4,9,4],
                   [4,5,9,7],
                   [2,9,4,3]])
print(arr,"\n")
print(repr(arr))
out=repr(arr).count("9, 4") #" " in this the svlue string must match the pattern in the repr(arr)
print(out)

[[2 8 9 4]
 [9 4 9 4]
 [4 5 9 7]
 [2 9 4 3]] 

array([[2, 8, 9, 4],
       [9, 4, 9, 4],
       [4, 5, 9, 7],
       [2, 9, 4, 3]])
4


In [63]:
arr = np.array([1,2,3,2,2,3,1,1,1,1,4,5,3,2])
print(np.bincount(arr))
print(np.unique(arr))
print("\nValues occuring most : ")
print(np.bincount(arr).argmax())
print("\nFrequency of occurance : ")
print(np.bincount(arr).max())
arr2 = np.array([1,2,3,2,2,3,1,1,1,2,1,4,5,3,2,])
print("\n",arr2)
y=np.bincount(arr2)
m = y.max()
a=0
for i in y:
    if(i == m):
        print(a)
    a+=1

[0 5 4 3 1 1]
[1 2 3 4 5]

Values occuring most : 
1

Frequency of occurance : 
5

 [1 2 3 2 2 3 1 1 1 2 1 4 5 3 2]
1
2


In [74]:
ar1 = np.array([1,2])
ar2 = np.arange(20).reshape(10,2)
print(ar1,"\n",ar2)
for x,y in np.nditer([ar1,ar2]):
    print("%d , %d"%(x,y))

[1 2] 
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
1 , 0
2 , 1
1 , 2
2 , 3
1 , 4
2 , 5
1 , 6
2 , 7
1 , 8
2 , 9
1 , 10
2 , 11
1 , 12
2 , 13
1 , 14
2 , 15
1 , 16
2 , 17
1 , 18
2 , 19


In [93]:
arr1 = np.array([1,2])
arr2 = np.array([3,4])
print(np.array(np.meshgrid(arr1,arr2)))
print(np.array(np.meshgrid(arr1,arr2)).T)
print(np.array(np.meshgrid(arr1,arr2)).T.reshape(-1,2))

[[[1 2]
  [1 2]]

 [[3 3]
  [4 4]]]
[[[1 3]
  [1 4]]

 [[2 3]
  [2 4]]]
[[1 3]
 [1 4]
 [2 3]
 [2 4]]


In [97]:
#adding a border to an array
arr = np.ones((3,3))
print(np.pad(arr,pad_width=1,mode='constant',constant_values =9))

[[9. 9. 9. 9. 9.]
 [9. 1. 1. 1. 9.]
 [9. 1. 1. 1. 9.]
 [9. 1. 1. 1. 9.]
 [9. 9. 9. 9. 9.]]


In [105]:
#comparing two array
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
comparison = arr1 == arr2
print(comparison)
eq = comparison.all()
print(eq)
a = np.array([101, 99, 87,34])
b = np.array([897, 97, 111,34])
print(np.greater(a,b))
print(np.greater_equal(a,b))
print(np.less(a,b))

[ True  True  True]
True
[False  True False False]
[False  True False  True]
[ True False  True False]


In [111]:
#using in keyword
arr= np.arange(12).reshape(3,4)
print(arr)
print(2 in arr)
print([4,5,6,7] in arr.tolist())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
True
True


In [119]:
#print diagonals of arrays
arr = np.arange(3*4*4).reshape(3,4,4)
print(arr)
print(np.diagonal(arr,axis1=1,axis2=2))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
[[ 0  5 10 15]
 [16 21 26 31]
 [32 37 42 47]]


In [125]:
#flatten an array
arr= np.arange(3*6).reshape(3,6)
print(arr)
print(arr.flatten(order='C'))
print(arr.flatten(order='F'))
print(arr.flatten(order='A'))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[ 0  6 12  1  7 13  2  8 14  3  9 15  4 10 16  5 11 17]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [132]:
#Fibonacci series 
num = int(input("Enter the number to fing Fibionacci series for : "))
a =np.arange(1,(num+1))
s = np.sqrt(5)
alpha = (1+np.sqrt(5))/2
beta = (1-np.sqrt(5))/2
Fn = np.rint(((alpha**a)-(beta**a))/s)
print("Fibonnaci series of first {} numbers is :{}".format(len(a),Fn))

Enter the number to fing Fibionacci series for : 10
Fibonnaci series of first 10 numbers is :[ 1.  1.  2.  3.  5.  8. 13. 21. 34. 55.]


In [137]:
arr = np.array([[1,2,0,3,4],[23,0,45,6,7]])
print(np.count_nonzero(arr)) #non zero elements in total
print(np.count_nonzero(arr,axis=1)) #non zero elements per row

8
[4 4]


In [141]:
#removing leading and tailing zeros 
arr = np.array([0, 0, 0, 0, 1, 5, 7, 0, 6, 2, 9, 0, 10, 0, 0])
print(np.trim_zeros(arr))
print(np.trim_zeros(arr,'f'))
print(np.trim_zeros(arr,'b'))

[ 1  5  7  0  6  2  9  0 10]
[ 1  5  7  0  6  2  9  0 10  0  0]
[ 0  0  0  0  1  5  7  0  6  2  9  0 10]


In [144]:
arr= np.array([1,2,3,4,5,6])
print(arr[::-1])
print(np.flipud(arr))

[6 5 4 3 2 1]
[6 5 4 3 2 1]


In [146]:
arr = np.random.randint(1,50,size=(4,5))
print(arr)
arr[arr<10] = 0
print("\n",arr)

[[39  4 35 44 11]
 [ 2 27 26 10 43]
 [ 2 42  5 45  6]
 [28 10 12 23  5]]

 [[39  0 35 44 11]
 [ 0 27 26 10 43]
 [ 0 42  0 45  0]
 [28 10 12 23  0]]


In [148]:
arr = np.random.randint(1,50,size=(4,5))
print(arr)
qa = np.where(arr<10,0,arr)
print(qa)

[[ 6 33 34 35  5]
 [18 37 14 35 19]
 [ 2 33  3 29  2]
 [38 46 16  8  4]]
[[ 0 33 34 35  0]
 [18 37 14 35 19]
 [ 0 33  0 29  0]
 [38 46 16  0  0]]


In [149]:
arr = np.arr = np.random.randint(1,10,size=(4,5))

In [163]:
print(arr)
q = np.where(arr<5)
print("Indices with values <5 \n")
for x,y in np.nditer([q[0],q[1]]):
    print("%d , %d"%(x,y))
print(arr[q])

[[3 2 5 3 2]
 [2 3 4 5 1]
 [4 7 6 7 6]
 [1 5 6 9 3]]
Indices with values <5 

0 , 0
0 , 1
0 , 3
0 , 4
1 , 0
1 , 1
1 , 2
1 , 4
2 , 0
3 , 0
3 , 4
[3 2 3 2 2 3 4 1 4 1 3]


In [178]:
arr = np.array([[1.3, 2.5, 3.6, np.nan], 
                      [2.6, 3.3, np.nan, 5.5],
                      [2.1, 3.2, 5.4, 6.5]])
print(arr)
colmean = np.nanmean(arr,axis = 0)
print(colmean)
ind = np.where(np.isnan(arr))
print(ind)
arr[ind]=np.take(colmean,ind[1])
print("\n",arr)

[[1.3 2.5 3.6 nan]
 [2.6 3.3 nan 5.5]
 [2.1 3.2 5.4 6.5]]
[2.  3.  4.5 6. ]
(array([0, 1]), array([3, 2]))

 [[1.3 2.5 3.6 6. ]
 [2.6 3.3 4.5 5.5]
 [2.1 3.2 5.4 6.5]]


In [183]:
arr = np.array([[1.3, 2.5, 3.6, np.nan], 
                      [2.6, 3.3, np.nan, 5.5],
                      [2.1, 3.2, 5.4, 6.5]])
print(arr)
print("\n",np.ma.array(arr,mask=np.isnan(arr)))
print("\n",np.ma.array(arr,mask=np.isnan(arr)).mean(axis=0))
re = np.where(np.isnan(arr),np.ma.array(arr,mask=np.isnan(arr)).mean(axis=0),arr)
print(re)

[[1.3 2.5 3.6 nan]
 [2.6 3.3 nan 5.5]
 [2.1 3.2 5.4 6.5]]

 [[1.3 2.5 3.6 --]
 [2.6 3.3 -- 5.5]
 [2.1 3.2 5.4 6.5]]

 [2.0 3.0 4.5 6.0]
[[1.3 2.5 3.6 6. ]
 [2.6 3.3 4.5 5.5]
 [2.1 3.2 5.4 6.5]]


In [186]:
#change values at a certain index
arr1 = np.array([1,23,34,12,5])
arr2 = np.array([2,24,45])
arr1.put([1,2],arr2)
print(arr1)
arr3 = np.array([[1,2,3,4],[5,6,7,8]])
arr3.put([1,4,6],arr2)
print(arr3)
a1 = np.array([[[11, 25, 7], [30, 45, 55], [20, 45, 7]],
               [[50, 65, 8], [70, 85, 10], [11, 22, 33]],
               [[19, 69, 36], [1, 5, 24], [4, 20, 9]]])
a2 = np.array([[1, 15, 10],
               [6, 40, 50],
               [11, 5, 10]])
a1.put([3,10,15,21],a2)
print(a1)

[ 1  2 24 12  5]
[[ 1  2  3  4]
 [24  6 45  8]]
[[[11 25  7]
  [ 1 45 55]
  [20 45  7]]

 [[50 15  8]
  [70 85 10]
  [10 22 33]]

 [[19 69 36]
  [ 6  5 24]
  [ 4 20  9]]]


In [187]:
a1 = np.array([[11, 10, 22],   
               [14, 58, 88]])
  
print("Array 1 :")
print(a1)
  
a2 = np.array([[1, 15, 6],
               [40, 50, 70]])
a1.put([1,20],a2,mode = 'clip') #if limit is out of bounds clip it to last element
print(a1)

Array 1 :
[[11 10 22]
 [14 58 88]]
[[11  1 22]
 [14 58 15]]


In [192]:
arr = np.array([[1,2,0,0,4,5],[4,0,7,8,0,9],[0,9,0,7,8,0]])
print(np.argwhere(arr == 0))

[[0 2]
 [0 3]
 [1 1]
 [1 4]
 [2 0]
 [2 2]
 [2 5]]


In [194]:
arr = np.array([10, 52, 62, 16, 16, 54, 453])
a = np.sort(arr)
print(a)
ab = np.argsort(arr)
print(ab)

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]


In [196]:
sm = int(input("Enter the kth for smallest value"))
sma = a[sm]
print(sma)

Enter the kth for smallest value2
16


In [198]:
arr= np.array(['Akash', 'Rohit', 'Ayush', 
                'Dhruv', 'Radhika'],dtype = np.str)
narr = np.char.multiply(arr,3)
print(arr)
print(narr)

['Akash' 'Rohit' 'Ayush' 'Dhruv' 'Radhika']
['AkashAkashAkash' 'RohitRohitRohit' 'AyushAyushAyush' 'DhruvDhruvDhruv'
 'RadhikaRadhikaRadhika']


In [199]:
arr = np.array(['Hello Hii Hey'],dtype=np.str)
n = np.char.split(arr)
print(n)

[list(['Hello', 'Hii', 'Hey'])]


In [200]:
arr = np.array(['Hello','Hey','Hii'],dtype = np.str)
n = np.char.join(" ",arr)
print(n)

['H e l l o' 'H e y' 'H i i']


In [201]:
a = [len(i) for i in arr]
print(a)

[5, 3, 3]


In [202]:
print(np.char.swapcase(arr))

['hELLO' 'hEY' 'hII']


In [203]:
sep = ['!','@','$']
n = np.char.join(sep,arr)
print(n)

['H!e!l!l!o' 'H@e@y' 'H$i$i']


In [206]:
in_arr = np.array(['Sayantan', '  Sayan  ', 'Sayansubhra'])
n = np.char.count(in_arr,sub='Sa')
print(n)

[1 1 1]


In [207]:
print(np.char.endswith(in_arr,"an"))

[ True False False]


In [ ]:
salesRecord = []
salesRecord_rows, salesRecord_cols  = map(int, raw_input().split())